-- ============================================================
-- 1. 插入台账数据 (T_SI_LEDGER)
-- ============================================================
-- 设备1: 正常设备，已上传标准
INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', '条盒拉线检测', '包装机组', 'ZB47 20#', 'GDGY 20#高速包装机组', '南京家泉', 'Ver5.3.2', '透明纸输送通道', '光电检测', 'JB000225', '320000192', '310001979', TO_DATE('2020-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

-- 设备2: 正常设备，已上传标准
INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', '光子缺失检测', '包装机组', 'ZB47 20#', 'GDGY 20#高速包装机组', '设备自管', 'JQYC10B', '条烟提升/输送通道', '视觉成像', 'JB000226', '320000193', '310001980', TO_DATE('2021-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

-- 设备3: 正常设备，无标准
INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', 'CT入口堆叠检测', '包装机组', 'ZB47 20#', 'GDGY 20#高速包装机组', 'KEYENCE', 'FS2-60P', 'CT入口通道', '激光测距', 'JB000227', '320000194', '310001981', TO_DATE('2018-01-01', 'YYYY-MM-DD'), '已归档', 0, SYSDATE);

-- 设备4: 正常设备，已上传标准
INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', '小包透明纸检测', '包装机组', 'ZB47 20#', 'GDGY 20#高速包装机组', 'KEYENCE', 'V31P', '透明纸输送通道', '光电开关', 'JB000228', '320000195', '310001982', TO_DATE('2018-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

-- 设备5: 正常设备，已上传标准
INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', '商标纸印刷检测', '包装机组', 'ZB47 20#', 'GDGY 20#高速包装机组', 'SICK', 'WT150', '商标纸输送通道', '色标传感器', 'JB000229', '320000196', '310001983', TO_DATE('2018-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

-- 设备6~10: 模拟其他设备
INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', '缺铝箔检测', '包装机组', 'ZB48 46#', 'GDGY 46#高速包装机组', 'OMRON', 'E3X-NA11', '铝箔纸输送通道', '光电检测', 'JB000230', '320000197', '310001984', TO_DATE('2019-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '卷包车间', '缺内框纸检测', '包装机组', 'ZB48 46#', 'GDGY 46#高速包装机组', 'SICK', 'KT5W', '内框纸输送通道', '色标传感器', 'JB000231', '320000198', '310001985', TO_DATE('2019-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '制丝车间', '润叶水分仪', '制丝机组', 'SJ152', '制丝生产线A', 'NDC', 'TM710', '润叶机出口', '红外水分', 'ZS000101', '320000200', '310002001', TO_DATE('2017-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '制丝车间', '烘丝出口电子秤', '制丝机组', 'SH812', '制丝生产线A', 'SCHENCK', 'MULTIBELT', '烘丝机出口', '皮带秤', 'ZS000102', '320000201', '310002002', TO_DATE('2017-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);

INSERT INTO T_SI_LEDGER (ID, WORKSHOP, NAME, MODEL, DEVICE, MAIN_DEVICE, FACTORY, SPEC, LOCATION, PRINCIPLE, PM_CODE, ORDER_NO, ASSET_CODE, FIRST_USE_DATE, AUDIT_STATUS, HAS_STANDARD, CREATE_TIME)
VALUES (SEQ_SI_LEDGER.NEXTVAL, '动力车间', '空压机1#', '空压机组', 'ATLAS', '动力空压站', 'Atlas Copco', 'GA160', '空压站房', '螺杆压缩', 'DL000301', '320000301', '310003001', TO_DATE('2016-01-01', 'YYYY-MM-DD'), '已归档', 1, SYSDATE);


-- ============================================================
-- 2. 插入标准明细数据 (T_SI_STANDARD)
-- 关联 Ledger ID: 假设上面插入的 ID 分别是 1~10 (如果序列已使用，请根据实际情况调整)
-- 这里我们为 ID=1 (条盒拉线检测) 和 ID=6 (缺铝箔检测) 插入标准
-- ============================================================

-- 为设备1 (条盒拉线检测) 插入标准
INSERT INTO T_SI_STANDARD (ID, LEDGER_ID, DEVICE_PART, ITEM_NAME, STANDARD_DESC, EXECUTOR_ROLE, CHECK_CYCLE, NEXT_EXEC_DATE)
VALUES (SEQ_SI_STANDARD.NEXTVAL, 1, '检测探头', '是否使用/删除功能', '功能打开; 能够准确剔除缺陷烟支', '包机电气维修工', 1, SYSDATE + 1);
INSERT INTO T_SI_STANDARD (ID, LEDGER_ID, DEVICE_PART, ITEM_NAME, STANDARD_DESC, EXECUTOR_ROLE, CHECK_CYCLE, NEXT_EXEC_DATE)
VALUES (SEQ_SI_STANDARD.NEXTVAL, 1, '检测探头', '检测信号波形', '波形清晰，无干扰信号', '包机电气维修工', 1, SYSDATE + 1);
INSERT INTO T_SI_STANDARD (ID, LEDGER_ID, DEVICE_PART, ITEM_NAME, STANDARD_DESC, EXECUTOR_ROLE, CHECK_CYCLE, NEXT_EXEC_DATE)
VALUES (SEQ_SI_STANDARD.NEXTVAL, 1, '剔除装置', '气压检查', '气压在 0.4-0.6 MPa 之间', '包机电气维修工', 1, SYSDATE + 1);

-- 为设备6 (缺铝箔检测) 插入标准
INSERT INTO T_SI_STANDARD (ID, LEDGER_ID, DEVICE_PART, ITEM_NAME, STANDARD_DESC, EXECUTOR_ROLE, CHECK_CYCLE, NEXT_EXEC_DATE)
VALUES (SEQ_SI_STANDARD.NEXTVAL, 6, '光纤放大器', '灵敏度调整', '能够准确识别有/无铝箔', '操作工', 1, SYSDATE + 1);
INSERT INTO T_SI_STANDARD (ID, LEDGER_ID, DEVICE_PART, ITEM_NAME, STANDARD_DESC, EXECUTOR_ROLE, CHECK_CYCLE, NEXT_EXEC_DATE)
VALUES (SEQ_SI_STANDARD.NEXTVAL, 6, '探头位置', '清洁度检查', '探头表面无积尘', '操作工', 1, SYSDATE + 1);


-- ============================================================
-- 3. 插入任务主表数据 (T_SI_TASK)
-- 模拟不同班次、不同状态的任务
-- ============================================================

-- 任务1: 待检 (今天, 早班, ZB47 20#)
INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CHECKER, CHECK_TIME, CONFIRMER, CONFIRM_TIME, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 1, '包装机组', 'ZB47 20#', '生产', '甲班', '早班', '待检', '待确认', TRUNC(SYSDATE), '三班电气', '否', NULL, NULL, NULL, NULL, SYSDATE);

-- 任务2: 已检未确认 (今天, 中班, ZB47 20#)
INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CHECKER, CHECK_TIME, CONFIRMER, CONFIRM_TIME, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 1, '包装机组', 'ZB47 20#', '生产', '甲班', '中班', '已检', '待确认', TRUNC(SYSDATE), '三班电气', '否', '张工', SYSDATE - 0.1, NULL, NULL, SYSDATE);

-- 任务3: 已检已确认 (昨天, 晚班, ZB48 46#)
INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CHECKER, CHECK_TIME, CONFIRMER, CONFIRM_TIME, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 6, '包装机组', 'ZB48 46#', '生产', '乙班', '晚班', '已检', '已确认', TRUNC(SYSDATE - 1), '三班电气', '否', '李工', SYSDATE - 1.1, '赵操作', SYSDATE - 1.05, SYSDATE - 1);

-- 任务4: 待检 (今天, 白班, ZB48 46#, 年检)
INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CHECKER, CHECK_TIME, CONFIRMER, CONFIRM_TIME, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 6, '包装机组', 'ZB48 46#', '停产', '白班', '-', '待检', '待确认', TRUNC(SYSDATE), '年检', '否', NULL, NULL, NULL, NULL, SYSDATE);

-- 任务5-10: 更多模拟数据...
INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 2, '包装机组', 'ZB47 20#', '生产', '甲班', '早班', '待检', '待确认', TRUNC(SYSDATE), '三班电气', '否', SYSDATE);

INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 3, '包装机组', 'ZB47 20#', '生产', '甲班', '早班', '待检', '待确认', TRUNC(SYSDATE), '三班电气', '否', SYSDATE);

INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 4, '包装机组', 'ZB47 20#', '生产', '甲班', '早班', '待检', '待确认', TRUNC(SYSDATE), '三班电气', '否', SYSDATE);

INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 5, '包装机组', 'ZB47 20#', '生产', '甲班', '早班', '待检', '待确认', TRUNC(SYSDATE), '三班电气', '否', SYSDATE);

INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 7, '包装机组', 'ZB48 46#', '生产', '甲班', '早班', '待检', '待确认', TRUNC(SYSDATE), '三班电气', '否', SYSDATE);

INSERT INTO T_SI_TASK (ID, LEDGER_ID, MODEL, DEVICE, PROD_STATUS, SHIFT_TYPE, SHIFT, CHECK_STATUS, CONFIRM_STATUS, TASK_TIME, TASK_TYPE, IS_OVERDUE, CREATE_TIME)
VALUES (SEQ_SI_TASK.NEXTVAL, 8, '制丝机组', 'SJ152', '生产', '丙班', '中班', '已检', '待确认', TRUNC(SYSDATE), '三班电气', '否', SYSDATE);


-- ============================================================
-- 4. 插入任务明细数据 (T_SI_TASK_DETAIL)
-- 仅为部分任务插入明细，以模拟不同进度
-- ============================================================

-- 为任务1 (待检) 插入 3 条明细 (未检)
-- 假设任务1的 ID 是 1 (如果序列已使用，请调整)
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 1, 'GDGY 20#高速包装机组', '条盒拉带存在检测', NULL, NULL, NULL, 0, NULL);
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 1, 'GDGY 20#高速包装机组', '条包空位检测', NULL, NULL, NULL, 0, NULL);
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 1, 'GDGY 20#高速包装机组', '条盒透明纸存在检测', NULL, NULL, NULL, 0, NULL);


-- 为任务2 (已检未确认) 插入 3 条明细
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 2, 'GDGY 20#高速包装机组', '条盒拉带存在检测', '正常', '运行平稳', SYSDATE - 0.1, 0, NULL);
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 2, 'GDGY 20#高速包装机组', '条包空位检测', '正常', NULL, SYSDATE - 0.1, 0, NULL);
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 2, 'GDGY 20#高速包装机组', '条盒透明纸存在检测', '异常', '感应器脏污', SYSDATE - 0.1, 0, NULL);


-- 为任务3 (已检已确认) 插入 3 条明细
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 3, 'GDGY 46#高速包装机组', '缺铝箔检测', '正常', NULL, SYSDATE - 1.1, 1, SYSDATE - 1.05);
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 3, 'GDGY 46#高速包装机组', '缺内框纸检测', '正常', NULL, SYSDATE - 1.1, 1, SYSDATE - 1.05);
INSERT INTO T_SI_TASK_DETAIL (ID, TASK_ID, MAIN_DEVICE, ITEM_NAME, CHECK_RESULT, CHECK_REMARKS, CHECK_TIME, IS_CONFIRMED, CONFIRM_TIME)
VALUES (SEQ_SI_TASK_DETAIL.NEXTVAL, 3, 'GDGY 46#高速包装机组', 'CH拉带存在检测', '不用', '该品牌无此项', SYSDATE - 1.1, 1, SYSDATE - 1.05);

COMMIT;